/*
CREATE TABLE SALES(salesid int primary key, country varchar(15), amount float);
INSERT INTO SALES VALUES
(1,'USA',500.00),
(2,'IND',1200.00),
(3,'CANADA',700.00),
(4,'UK',900.00),
(5,'IND',1500.00);

SELECT * FROM SALES;

SELECT COUNTRY, COUNT(COUNTRY) AS CountHistory FROM SALES GROUP BY country;

SELECT COUNTRY FROM SALES GROUP BY COUNTRY HAVING AVG(AMOUNT)<1000;

SELECT COUNTRY , AVG(AMOUNT) FROM SALES GROUP BY COUNTRY;

SELECT COUNTRY, SUM(AMOUNT) FROM SALES GROUP BY COUNTRY;

SELECT COUNTRY ,COUNT(*) AS CNT FROM SALES GROUP BY COUNTRY;

*/
CREATE TABLE EMP1(Department varchar(50), salary decimal(10,2));
INSERT INTO EMP1 VALUES
('SALES',1000.00),
('SALES',300.00),
('SALES',3000.00),
('HR',2000.00),
('HR',5000.00),
('SALES',4500.00),
('IT',1000.00),
('IT',1000.00);

SELECT * FROM EMP1;

SELECT Department,SUM(SALARY) FROM EMP1 GROUP BY DEPARTMENT;
SELECT DEPARTMENT,AVG(SALARY) AS AVGSAL FROM EMP1 GROUP BY Department;

