CREATE TABLE STUDENTS(STUDENTID int, FIRSTNAME varchar(15),LASTNAME varchar(15),Age int, GPA decimal(3,2));
INSERT INTO STUDENTS VALUES
(1,'John','Smit',20,3.75),
(2,'Emily','Johnson',22,3.90),
(3,'Michael','Davis',21,3.60);

SELECT * FROM STUDENTS;

CREATE TABLE COURSES(COURSEID int,COURSENAME varchar(20),Credits int);
INSERT INTO COURSES VALUES
(101,'Marhematics',3),
(102,'History',4),
(103,'Computer Science',3);

SELECT * FROM COURSES;

CREATE TABLE ENROLLEMENTS(ENROLLEMENTID int, STUDENTID int, COURSEID int, ENROLLEMENTDATE datetime);
INSERT INTO ENROLLEMENTS VALUES
(1,1,101,'2023-01-15 10:30:00'),
(2,2,102,'2023-02-20 14:45:00'),
(3,1,103,'2023-03-05 08:15:00');

SELECT * FROM ENROLLEMENTS;

-- Question 1
SELECT * FROM STUDENTS WHERE GPA > 3.7;

-- Question 2
SELECT STUDENTID, SUM(Credits) AS SUMCREDITS FROM COURSES INNER JOIN ENROLLEMENTS ON COURSES.COURSEID = ENROLLEMENTS.COURSEID GROUP BY STUDENTID;

-- Question 3
SELECT * FROM ENROLLEMENTS WHERE COURSEID = (SELECT COURSEID FROM COURSES WHERE COURSENAME='Marhematics');

-- Question 4
/*
SELECT * FROM student
JOIN student_course
  ON student.id = student_course.student_id
JOIN course
  ON course.id = student_course.course_id;
  */

  SELECT AVG(Age) FROM COURSES JOIN ENROLLEMENTS ON COURSES.COURSEID = ENROLLEMENTS.COURSEID
  JOIN STUDENTS ON STUDENTS.STUDENTID = ENROLLEMENTS.ENROLLEMENTID GROUP BY COURSENAME HAVING COURSENAME='Computer Science';

--QUESTION 5
UPDATE STUDENTS SET GPA = GPA+0.1;
SELECT * FROM STUDENTS;


--QUESTION 6
  SELECT coursename,COUNT(STUDENTS.STUDENTID) AS HighestEnroll FROM STUDENTS FULL OUTER JOIN ENROLLEMENTS ON STUDENTS.STUDENTID = ENROLLEMENTS.STUDENTID INNER JOIN COURSES ON COURSES.COURSEID = ENROLLEMENTS.COURSEID GROUP BY COURSES.COURSENAME;